### ISSUE TITLE
Roadmap for version 1.0.0

### ISSUE THREAD

**Issue by mpizenberg** [mpizenberg/elm-tensor#4]
- [x] Write the roadmap XD
 - [ ] (cf #1) Complete matrices functions
 - [x] (cf #2) Complete matrices fuzzers for tests
 - [ ] (cf #3) Complete tests
 - [ ] (cf #5) Write benchmarks comparing with other matrix package
 - [ ] Change with feedback
